version: '3.8'

services:

  web:
    build: .
    command: bash -c "sleep 15 && alembic upgrade head && uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"
    ports:
      - 8004:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    hostname: postgres
    image: postgres:15.3
    expose:
      - 5432
    env_file:
      - .env